name: Tag and Release on Version Change

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Creates a new tag when a new version is discovered in package.json
    - uses: butlerlogic/action-autotag@stable
      id: autotag
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
    # Creates a new release only when a new tag was just created
    - uses: actions/create-release@v1
      id: autorelease
      if: steps.autotag.outputs.tagname != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.autotag.outputs.tagname }}
        release_name: Release ${{ steps.autotag.outputs.tagname }}
        draft: false
        prerelease: false
